### ISSUE TITLE
API/CLI available?

### ISSUE THREAD

**Issue by PaulieMac** [octarinesec/kube-scan#26]
Hi!

I was wondering if there is an API or CLI available? This would make this tool truly awesome (it is already very cool) because then we could use it in our CD pipelines, i.e.  (with kube-scan stuff marked with **** ):

->build my stack
->deploy my stack into k8s
->**** trigger  kube-scan via api somehow, with a 'query', i.e. ?k8namespace='build_579'&workload='myNewWorkload'
->**** collect  kube-scan results, and fail or pass depending on...?

->mark build as red or green,

Many thanks!

Paul

**Comment by BenRub** [comment]
Hi Paul,

After installing kube-scan as part of your pipeline, you can use the following API:
https://github.com/octarinesec/kube-scan#using-the-api

Right now, there's no api to scan a specific workload.

Thanks,
Ben.

**Comment by PaulieMac** [comment]
Apologies, I had not noted that line in the docs!
