### ISSUE TITLE
PodSecurityPolicy injected defaults are not considered for zero-replica workloads

### ISSUE THREAD

**Issue by drakedevel** [octarinesec/kube-scan#6]
In addition to restricting the privileges pods can request, PodSecurityPolicies can inject default settings into pods as they're created. For example, a PodSecurityPolicy with `runAsUser: {rule 'MustRunAsNonRoot'}` will actually add `runAsNonRoot: true` to a Pod's spec at admission time if nothing limiting the user is already present.

In our cluster, most of our deployments are authorized by a shared PodSecurityPolicy with very restrictive defaults. It enables seccomp, drops capabilities, prohibits running as root, disables privilege escalation, disables most volume types, and so on. When we ran kube-scan on a test cluster, we were surprised to see that many of our deployments had triggered rules that should have been prevented by this PodSecurityPolicy.

For our Deployments with zero replicas, we get false positives for these rules:
- AllowPrivilegeEscalation
- runningAsRoot
- CapNetRaw

We also don't see the seccomp mitigation, even though this is added by our PodSecurityPolicy.

To correctly evaluate these rules with no replicas, it's necessary to enumerate the PodSecurityPolicies that the relevant ServiceAccount has access to, and check whether any of those permit the offending behavior.

This is possibly a separate bug, but even for our deployments with non-zero replicas, we get false positives on the runningAsRoot rule. For every pod in the Deployment, I manually confirmed that every container and initContainer has `securityContext: {runAsNonRoot: true}` (as enforced by the PodSecurityPolicy), but the rule still fires. Other injected defaults like AllowPrivilegeEscalation and seccomp seem to be correctly detected in this case.

Let me know if you need any more information!

**Comment by RazOmessi** [comment]
Hi @drakedevel,

Thank you for opening the issue!
We pushed a commit that solves the false-positive problem for workloads with at least 1 replicas.

About workloads with no replicas,
Trying to simulate the effect of podSecurityPolicy and other mutating admission controllers seems error prone.
Since such workloads don’t really introduce risk, we will remove them from the risk report.
I’m not closing the issue for now.

**Comment by drakedevel** [comment]
>Trying to simulate the effect of podSecurityPolicy and other mutating admission controllers seems error prone.
>Since such workloads don’t really introduce risk, we will remove them from the risk report.

Agreed, and sounds like a good workaround to me. Thanks!
